version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dental-clinic-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dental-clinic-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dental-clinic-frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend